# Generated by Django 3.0.5 on 2023-08-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertasks',
            name='title',
        ),
    ]
